// ============================================================
//  app/cartSlice.js — the shopping cart (Redux Toolkit slice)
//  ============================================================
//  Our brief compared Redux to a "central storage locker in the
//  browser". This slice IS that locker for the cart: it holds the
//  cart items and defines the ACTIONS to change them.
//
//  LEARNING NOTE — Redux Toolkit (RTK) fundamentals:
//  - "State": the single source of truth (here: the cart array).
//  - "Action": a plain object describing an intent, e.g.
//    { type: 'cart/addItem', payload: {...} }.
//  - "Reducer": a pure function that takes the current state + an
//    action and returns the NEW state. Pure = no side effects, so it
//    is predictable & testable.
//  - RTK's createSlice generates actions + reducers together and uses
//    Immer under the hood, so we can write "mutating-looking" code
//    (state.items.push(...)) safely — Immer translates it to an
//    immutable update for us.
// ============================================================

import { createSlice } from '@reduxjs/toolkit';

// Initial state: an empty cart with a zero subtotal.
// We track two things:
//   items        : array of { product, name, price, qty, imageUrl, stock }
//   itemsCount   : total number of units (sum of qty)
//   itemsSubtotal: total cost WITHOUT tax/shipping (computed here for UX;
//                  the SERVER recomputes the real total at checkout).
const initialState = {
  items: [],
  itemsCount: 0,
  itemsSubtotal: 0,
};

// A helper to recompute count/subtotal from the items array.
// It's a pure function used inside reducers to keep derived values
// in sync whenever items change.
const recompute = (items) => {
  return {
    itemsCount: items.reduce((sum, item) => sum + item.qty, 0),
    itemsSubtotal: items.reduce((sum, item) => sum + item.price * item.qty, 0),
  };
};

const cartSlice = createSlice({
  name: 'cart',
  initialState,

  // Reducers: each function handles one action type. The name matches
  // the action type, so `addItem` <-> action type 'cart/addItem'.
  reducers: {
    // ---- addItem: add an item or increment its quantity ----
    // payload: { product, name, price, imageUrl, qty, stock }
    addItem: (state, action) => {
      const { product, name, price, imageUrl, qty, stock } = action.payload;
      // Check if this product is already in the cart.
      const existing = state.items.find((item) => item.product === product);

      if (existing) {
        // Already there → increase its qty (cap at available stock).
        existing.qty = Math.min(existing.qty + qty, stock);
      } else {
        // New item → push it in (respect zero-stock guard).
        state.items.push({
          product,
          name,
          price,
          imageUrl,
          qty: Math.min(qty, stock),
          stock,
        });
      }
      // Recompute derived values after the mutation.
      Object.assign(state, recompute(state.items));
    },

    // ---- removeItem: drop an item entirely ----
    // payload: product id
    removeItem: (state, action) => {
      state.items = state.items.filter((item) => item.product !== action.payload);
      Object.assign(state, recompute(state.items));
    },

    // ---- setQty: set an exact quantity for an item ----
    // payload: { product, qty }
    setQty: (state, action) => {
      const { product, qty } = action.payload;
      const existing = state.items.find((item) => item.product === product);
      if (existing) {
        // Clamp between 1 and available stock.
        existing.qty = Math.max(1, Math.min(qty, existing.stock));
      }
      Object.assign(state, recompute(state.items));
    },

    // ---- clearCart: empty the cart after a successful order ----
    clearCart: (state) => {
      state.items = [];
      Object.assign(state, recompute(state.items));
    },
  },
});

// Export the action creators (auto-generated by createSlice).
export const { addItem, removeItem, setQty, clearCart } = cartSlice.actions;

// ---- Selectors ----
// A "selector" is a function that pulls a piece of state out. Using
// selectors keeps components decoupled from the state shape.
export const selectCartItems = (state) => state.cart.items;
export const selectCartCount = (state) => state.cart.itemsCount;
export const selectCartSubtotal = (state) => state.cart.itemsSubtotal;

// Default-export the reducer so the store can combine it.
export default cartSlice.reducer;
