// AUTO-GENERATED by generateSeed.js — do not edit by hand.
// Re-run `node server/src/generateSeed.js` from the repo root to regenerate.
const products = [
  {
    "name": "Bluetooth Solar Keyboard",
    "description": "Premium electronics item. Bluetooth Solar Keyboard — quality you can trust, backed by a friendly return policy.",
    "price": 126.37,
    "category": "Electronics",
    "stock": 13,
    "imageUrl": "/images/logo-0.svg"
  },
  {
    "name": "Adjustable Bamboo Ottoman",
    "description": "Premium furniture item. Adjustable Bamboo Ottoman — quality you can trust, backed by a friendly return policy.",
    "price": 895.85,
    "category": "Furniture",
    "stock": 32,
    "imageUrl": "/images/logo-1.svg"
  },
  {
    "name": "Durable Gift Earrings",
    "description": "Premium wearables item. Durable Gift Earrings — quality you can trust, backed by a friendly return policy.",
    "price": 53.14,
    "category": "Wearables",
    "stock": 191,
    "imageUrl": "/images/logo-2.svg"
  },
  {
    "name": "Stone-Ground Fresh Dark Chocolate",
    "description": "Premium groceries item. Stone-Ground Fresh Dark Chocolate — quality you can trust, backed by a friendly return policy.",
    "price": 19.55,
    "category": "Groceries",
    "stock": 107,
    "imageUrl": "/images/logo-3.svg"
  },
  {
    "name": "Compact Recycled Wallet",
    "description": "Premium accessories item. Compact Recycled Wallet — quality you can trust, backed by a friendly return policy.",
    "price": 167.46,
    "category": "Accessories",
    "stock": 34,
    "imageUrl": "/images/logo-4.svg"
  },
  {
    "name": "Modern Energy-Saving Food Storage",
    "description": "Premium home & kitchen item. Modern Energy-Saving Food Storage — quality you can trust, backed by a friendly return policy.",
    "price": 213.68,
    "category": "Home & Kitchen",
    "stock": 55,
    "imageUrl": "/images/logo-5.svg"
  },
  {
    "name": "Spa Tea Tree Face Mask",
    "description": "Premium beauty & personal care item. Spa Tea Tree Face Mask — quality you can trust, backed by a friendly return policy.",
    "price": 95.99,
    "category": "Beauty & Personal Care",
    "stock": 129,
    "imageUrl": "/images/logo-6.svg"
  },
  {
    "name": "Lightweight Reinforced Tent",
    "description": "Premium sports & outdoors item. Lightweight Reinforced Tent — quality you can trust, backed by a friendly return policy.",
    "price": 59.76,
    "category": "Sports & Outdoors",
    "stock": 92,
    "imageUrl": "/images/logo-7.svg"
  },
  {
    "name": "Retro Beginner Building Set",
    "description": "Premium toys & games item. Retro Beginner Building Set — quality you can trust, backed by a friendly return policy.",
    "price": 41.01,
    "category": "Toys & Games",
    "stock": 72,
    "imageUrl": "/images/logo-8.svg"
  },
  {
    "name": "Premium Fountain-Pen Planner",
    "description": "Premium books & stationery item. Premium Fountain-Pen Planner — quality you can trust, backed by a friendly return policy.",
    "price": 19.87,
    "category": "Books & Stationery",
    "stock": 171,
    "imageUrl": "/images/logo-9.svg"
  },
  {
    "name": "Water-Resistant Reflective Pet Carrier",
    "description": "Premium pet supplies item. Water-Resistant Reflective Pet Carrier — quality you can trust, backed by a friendly return policy.",
    "price": 186.1,
    "category": "Pet Supplies",
    "stock": 167,
    "imageUrl": "/images/logo-10.svg"
  },
  {
    "name": "Portable Dash-Cam Jump Starter",
    "description": "Premium automotive item. Portable Dash-Cam Jump Starter — quality you can trust, backed by a friendly return policy.",
    "price": 99.11,
    "category": "Automotive",
    "stock": 76,
    "imageUrl": "/images/logo-11.svg"
  },
  {
    "name": "Wireless Solar Keyboard",
    "description": "Premium electronics item. Wireless Solar Keyboard — quality you can trust, backed by a friendly return policy.",
    "price": 354.49,
    "category": "Electronics",
    "stock": 39,
    "imageUrl": "/images/logo-12.svg"
  },
  {
    "name": "Rustic Leather Cabinet",
    "description": "Premium furniture item. Rustic Leather Cabinet — quality you can trust, backed by a friendly return policy.",
    "price": 743.69,
    "category": "Furniture",
    "stock": 52,
    "imageUrl": "/images/logo-13.svg"
  },
  {
    "name": "Fitness Heart-Rate Ring",
    "description": "Premium wearables item. Fitness Heart-Rate Ring — quality you can trust, backed by a friendly return policy.",
    "price": 224.65,
    "category": "Wearables",
    "stock": 198,
    "imageUrl": "/images/logo-14.svg"
  },
  {
    "name": "Hand-Crafted Gluten-Free Honey",
    "description": "Premium groceries item. Hand-Crafted Gluten-Free Honey — quality you can trust, backed by a friendly return policy.",
    "price": 7.07,
    "category": "Groceries",
    "stock": 255,
    "imageUrl": "/images/logo-15.svg"
  },
  {
    "name": "Compact Recycled Wallet",
    "description": "Premium accessories item. Compact Recycled Wallet — quality you can trust, backed by a friendly return policy.",
    "price": 82.28,
    "category": "Accessories",
    "stock": 133,
    "imageUrl": "/images/logo-16.svg"
  },
  {
    "name": "Stainless Tempered Coffee Maker",
    "description": "Premium home & kitchen item. Stainless Tempered Coffee Maker — quality you can trust, backed by a friendly return policy.",
    "price": 87.53,
    "category": "Home & Kitchen",
    "stock": 42,
    "imageUrl": "/images/logo-17.svg"
  },
  {
    "name": "Natural Aloe Face Mask",
    "description": "Premium beauty & personal care item. Natural Aloe Face Mask — quality you can trust, backed by a friendly return policy.",
    "price": 51.47,
    "category": "Beauty & Personal Care",
    "stock": 86,
    "imageUrl": "/images/logo-18.svg"
  },
  {
    "name": "Portable Insulated Sleeping Bag",
    "description": "Premium sports & outdoors item. Portable Insulated Sleeping Bag — quality you can trust, backed by a friendly return policy.",
    "price": 245.23,
    "category": "Sports & Outdoors",
    "stock": 62,
    "imageUrl": "/images/logo-19.svg"
  },
  {
    "name": "Buildable Bluetooth Building Set",
    "description": "Premium toys & games item. Buildable Bluetooth Building Set — quality you can trust, backed by a friendly return policy.",
    "price": 120.94,
    "category": "Toys & Games",
    "stock": 132,
    "imageUrl": "/images/logo-20.svg"
  },
  {
    "name": "Classic Lined Pen Set",
    "description": "Premium books & stationery item. Classic Lined Pen Set — quality you can trust, backed by a friendly return policy.",
    "price": 45.5,
    "category": "Books & Stationery",
    "stock": 268,
    "imageUrl": "/images/logo-21.svg"
  },
  {
    "name": "Comfort Ergonomic Grooming Brush",
    "description": "Premium pet supplies item. Comfort Ergonomic Grooming Brush — quality you can trust, backed by a friendly return policy.",
    "price": 63.56,
    "category": "Pet Supplies",
    "stock": 128,
    "imageUrl": "/images/logo-22.svg"
  },
  {
    "name": "Heavy-Duty Magnetic Car Vacuum",
    "description": "Premium automotive item. Heavy-Duty Magnetic Car Vacuum — quality you can trust, backed by a friendly return policy.",
    "price": 232.97,
    "category": "Automotive",
    "stock": 15,
    "imageUrl": "/images/logo-23.svg"
  },
  {
    "name": "Noise-Cancelling USB-C Keyboard",
    "description": "Premium electronics item. Noise-Cancelling USB-C Keyboard — quality you can trust, backed by a friendly return policy.",
    "price": 340.46,
    "category": "Electronics",
    "stock": 45,
    "imageUrl": "/images/logo-24.svg"
  },
  {
    "name": "Modern Metal Desk",
    "description": "Premium furniture item. Modern Metal Desk — quality you can trust, backed by a friendly return policy.",
    "price": 767.73,
    "category": "Furniture",
    "stock": 55,
    "imageUrl": "/images/logo-25.svg"
  },
  {
    "name": "Durable Anti-bacterial Earbuds",
    "description": "Premium wearables item. Durable Anti-bacterial Earbuds — quality you can trust, backed by a friendly return policy.",
    "price": 393.62,
    "category": "Wearables",
    "stock": 160,
    "imageUrl": "/images/logo-26.svg"
  },
  {
    "name": "Organic Roasted Dark Chocolate",
    "description": "Premium groceries item. Organic Roasted Dark Chocolate — quality you can trust, backed by a friendly return policy.",
    "price": 25.74,
    "category": "Groceries",
    "stock": 46,
    "imageUrl": "/images/logo-27.svg"
  },
  {
    "name": "Compact Adjustable Belt",
    "description": "Premium accessories item. Compact Adjustable Belt — quality you can trust, backed by a friendly return policy.",
    "price": 118.57,
    "category": "Accessories",
    "stock": 27,
    "imageUrl": "/images/logo-28.svg"
  },
  {
    "name": "Smart Energy-Saving Blender",
    "description": "Premium home & kitchen item. Smart Energy-Saving Blender — quality you can trust, backed by a friendly return policy.",
    "price": 45.1,
    "category": "Home & Kitchen",
    "stock": 42,
    "imageUrl": "/images/logo-29.svg"
  },
  {
    "name": "Vitamin-Enriched Lavender Lip Balm",
    "description": "Premium beauty & personal care item. Vitamin-Enriched Lavender Lip Balm — quality you can trust, backed by a friendly return policy.",
    "price": 126.66,
    "category": "Beauty & Personal Care",
    "stock": 162,
    "imageUrl": "/images/logo-30.svg"
  },
  {
    "name": "Durable Insulated Dumbbell Set",
    "description": "Premium sports & outdoors item. Durable Insulated Dumbbell Set — quality you can trust, backed by a friendly return policy.",
    "price": 367.88,
    "category": "Sports & Outdoors",
    "stock": 87,
    "imageUrl": "/images/logo-31.svg"
  },
  {
    "name": "Interactive Magnetic RC Car",
    "description": "Premium toys & games item. Interactive Magnetic RC Car — quality you can trust, backed by a friendly return policy.",
    "price": 41.14,
    "category": "Toys & Games",
    "stock": 63,
    "imageUrl": "/images/logo-32.svg"
  },
  {
    "name": "Bestselling Grid Pencil Case",
    "description": "Premium books & stationery item. Bestselling Grid Pencil Case — quality you can trust, backed by a friendly return policy.",
    "price": 63.64,
    "category": "Books & Stationery",
    "stock": 235,
    "imageUrl": "/images/logo-33.svg"
  },
  {
    "name": "Water-Resistant Ergonomic Leash",
    "description": "Premium pet supplies item. Water-Resistant Ergonomic Leash — quality you can trust, backed by a friendly return policy.",
    "price": 71.73,
    "category": "Pet Supplies",
    "stock": 101,
    "imageUrl": "/images/logo-34.svg"
  },
  {
    "name": "Portable Solar Tire Pump",
    "description": "Premium automotive item. Portable Solar Tire Pump — quality you can trust, backed by a friendly return policy.",
    "price": 243.96,
    "category": "Automotive",
    "stock": 114,
    "imageUrl": "/images/logo-35.svg"
  },
  {
    "name": "Pro Solar Keyboard",
    "description": "Premium electronics item. Pro Solar Keyboard — quality you can trust, backed by a friendly return policy.",
    "price": 267.69,
    "category": "Electronics",
    "stock": 11,
    "imageUrl": "/images/logo-36.svg"
  },
  {
    "name": "Adjustable Bamboo Ottoman",
    "description": "Premium furniture item. Adjustable Bamboo Ottoman — quality you can trust, backed by a friendly return policy.",
    "price": 239.38,
    "category": "Furniture",
    "stock": 59,
    "imageUrl": "/images/logo-37.svg"
  },
  {
    "name": "Durable Anti-bacterial Watch",
    "description": "Premium wearables item. Durable Anti-bacterial Watch — quality you can trust, backed by a friendly return policy.",
    "price": 209.57,
    "category": "Wearables",
    "stock": 187,
    "imageUrl": "/images/logo-38.svg"
  },
  {
    "name": "Artisan Cold-Pressed Almond Butter",
    "description": "Premium groceries item. Artisan Cold-Pressed Almond Butter — quality you can trust, backed by a friendly return policy.",
    "price": 87.76,
    "category": "Groceries",
    "stock": 71,
    "imageUrl": "/images/logo-39.svg"
  },
  {
    "name": "Water-Resistant Recycled Keychain",
    "description": "Premium accessories item. Water-Resistant Recycled Keychain — quality you can trust, backed by a friendly return policy.",
    "price": 175.85,
    "category": "Accessories",
    "stock": 41,
    "imageUrl": "/images/logo-40.svg"
  },
  {
    "name": "Elegant Tempered Cutlery Set",
    "description": "Premium home & kitchen item. Elegant Tempered Cutlery Set — quality you can trust, backed by a friendly return policy.",
    "price": 149.89,
    "category": "Home & Kitchen",
    "stock": 95,
    "imageUrl": "/images/logo-41.svg"
  },
  {
    "name": "Long-Lasting Charcoal Suncreen",
    "description": "Premium beauty & personal care item. Long-Lasting Charcoal Suncreen — quality you can trust, backed by a friendly return policy.",
    "price": 35.49,
    "category": "Beauty & Personal Care",
    "stock": 161,
    "imageUrl": "/images/logo-42.svg"
  },
  {
    "name": "All-Weather Reinforced Tent",
    "description": "Premium sports & outdoors item. All-Weather Reinforced Tent — quality you can trust, backed by a friendly return policy.",
    "price": 64.79,
    "category": "Sports & Outdoors",
    "stock": 105,
    "imageUrl": "/images/logo-43.svg"
  },
  {
    "name": "Educational Collector Puzzle",
    "description": "Premium toys & games item. Educational Collector Puzzle — quality you can trust, backed by a friendly return policy.",
    "price": 107.98,
    "category": "Toys & Games",
    "stock": 97,
    "imageUrl": "/images/logo-44.svg"
  },
  {
    "name": "Illustrated Lined Notebook",
    "description": "Premium books & stationery item. Illustrated Lined Notebook — quality you can trust, backed by a friendly return policy.",
    "price": 68.25,
    "category": "Books & Stationery",
    "stock": 137,
    "imageUrl": "/images/logo-45.svg"
  },
  {
    "name": "No-Pull Reflective Pet Toy",
    "description": "Premium pet supplies item. No-Pull Reflective Pet Toy — quality you can trust, backed by a friendly return policy.",
    "price": 61.23,
    "category": "Pet Supplies",
    "stock": 174,
    "imageUrl": "/images/logo-46.svg"
  },
  {
    "name": "Portable Rechargeable Phone Mount",
    "description": "Premium automotive item. Portable Rechargeable Phone Mount — quality you can trust, backed by a friendly return policy.",
    "price": 64.3,
    "category": "Automotive",
    "stock": 53,
    "imageUrl": "/images/logo-47.svg"
  },
  {
    "name": "Pro OLED Monitor",
    "description": "Premium electronics item. Pro OLED Monitor — quality you can trust, backed by a friendly return policy.",
    "price": 42.78,
    "category": "Electronics",
    "stock": 71,
    "imageUrl": "/images/logo-48.svg"
  },
  {
    "name": "Velvet Bamboo Nightstand",
    "description": "Premium furniture item. Velvet Bamboo Nightstand — quality you can trust, backed by a friendly return policy.",
    "price": 123.73,
    "category": "Furniture",
    "stock": 20,
    "imageUrl": "/images/logo-49.svg"
  },
  {
    "name": "Wireless Gift Necklace",
    "description": "Premium wearables item. Wireless Gift Necklace — quality you can trust, backed by a friendly return policy.",
    "price": 42.82,
    "category": "Wearables",
    "stock": 48,
    "imageUrl": "/images/logo-50.svg"
  },
  {
    "name": "Artisan Gluten-Free Green Tea",
    "description": "Premium groceries item. Artisan Gluten-Free Green Tea — quality you can trust, backed by a friendly return policy.",
    "price": 37.98,
    "category": "Groceries",
    "stock": 238,
    "imageUrl": "/images/logo-51.svg"
  },
  {
    "name": "Vintage Reinforced Watch Strap",
    "description": "Premium accessories item. Vintage Reinforced Watch Strap — quality you can trust, backed by a friendly return policy.",
    "price": 46.06,
    "category": "Accessories",
    "stock": 137,
    "imageUrl": "/images/logo-52.svg"
  },
  {
    "name": "Elegant Tempered Coffee Maker",
    "description": "Premium home & kitchen item. Elegant Tempered Coffee Maker — quality you can trust, backed by a friendly return policy.",
    "price": 103.87,
    "category": "Home & Kitchen",
    "stock": 76,
    "imageUrl": "/images/logo-53.svg"
  },
  {
    "name": "Vitamin-Enriched Shea Skincare Set",
    "description": "Premium beauty & personal care item. Vitamin-Enriched Shea Skincare Set — quality you can trust, backed by a friendly return policy.",
    "price": 88.64,
    "category": "Beauty & Personal Care",
    "stock": 250,
    "imageUrl": "/images/logo-54.svg"
  },
  {
    "name": "Durable Reinforced Cycling Helmet",
    "description": "Premium sports & outdoors item. Durable Reinforced Cycling Helmet — quality you can trust, backed by a friendly return policy.",
    "price": 223.08,
    "category": "Sports & Outdoors",
    "stock": 19,
    "imageUrl": "/images/logo-55.svg"
  },
  {
    "name": "Interactive Battery-Powered Action Figure",
    "description": "Premium toys & games item. Interactive Battery-Powered Action Figure — quality you can trust, backed by a friendly return policy.",
    "price": 101.45,
    "category": "Toys & Games",
    "stock": 171,
    "imageUrl": "/images/logo-56.svg"
  },
  {
    "name": "Notebook Dotted Pencil Case",
    "description": "Premium books & stationery item. Notebook Dotted Pencil Case — quality you can trust, backed by a friendly return policy.",
    "price": 43.27,
    "category": "Books & Stationery",
    "stock": 77,
    "imageUrl": "/images/logo-57.svg"
  },
  {
    "name": "Durable Adjustable Grooming Brush",
    "description": "Premium pet supplies item. Durable Adjustable Grooming Brush — quality you can trust, backed by a friendly return policy.",
    "price": 72.47,
    "category": "Pet Supplies",
    "stock": 88,
    "imageUrl": "/images/logo-58.svg"
  },
  {
    "name": "Portable Dash-Cam Floor Mats",
    "description": "Premium automotive item. Portable Dash-Cam Floor Mats — quality you can trust, backed by a friendly return policy.",
    "price": 263.26,
    "category": "Automotive",
    "stock": 88,
    "imageUrl": "/images/logo-59.svg"
  },
  {
    "name": "4K Ultra HD Speaker",
    "description": "Premium electronics item. 4K Ultra HD Speaker — quality you can trust, backed by a friendly return policy.",
    "price": 247.26,
    "category": "Electronics",
    "stock": 150,
    "imageUrl": "/images/logo-60.svg"
  },
  {
    "name": "Adjustable Wicker Cabinet",
    "description": "Premium furniture item. Adjustable Wicker Cabinet — quality you can trust, backed by a friendly return policy.",
    "price": 525.82,
    "category": "Furniture",
    "stock": 20,
    "imageUrl": "/images/logo-61.svg"
  },
  {
    "name": "Fitness Travel Earrings",
    "description": "Premium wearables item. Fitness Travel Earrings — quality you can trust, backed by a friendly return policy.",
    "price": 104.54,
    "category": "Wearables",
    "stock": 72,
    "imageUrl": "/images/logo-62.svg"
  },
  {
    "name": "Stone-Ground Small-Batch Green Tea",
    "description": "Premium groceries item. Stone-Ground Small-Batch Green Tea — quality you can trust, backed by a friendly return policy.",
    "price": 64.79,
    "category": "Groceries",
    "stock": 298,
    "imageUrl": "/images/logo-63.svg"
  },
  {
    "name": "Handmade Waterproof Wallet",
    "description": "Premium accessories item. Handmade Waterproof Wallet — quality you can trust, backed by a friendly return policy.",
    "price": 163.4,
    "category": "Accessories",
    "stock": 102,
    "imageUrl": "/images/logo-64.svg"
  },
  {
    "name": "Insulated Ceramic Cooking Pot",
    "description": "Premium home & kitchen item. Insulated Ceramic Cooking Pot — quality you can trust, backed by a friendly return policy.",
    "price": 81.61,
    "category": "Home & Kitchen",
    "stock": 31,
    "imageUrl": "/images/logo-65.svg"
  },
  {
    "name": "Hydrating Aloe Face Mask",
    "description": "Premium beauty & personal care item. Hydrating Aloe Face Mask — quality you can trust, backed by a friendly return policy.",
    "price": 30.79,
    "category": "Beauty & Personal Care",
    "stock": 135,
    "imageUrl": "/images/logo-66.svg"
  },
  {
    "name": "Waterproof Insulated Yoga Mat",
    "description": "Premium sports & outdoors item. Waterproof Insulated Yoga Mat — quality you can trust, backed by a friendly return policy.",
    "price": 29.55,
    "category": "Sports & Outdoors",
    "stock": 112,
    "imageUrl": "/images/logo-67.svg"
  },
  {
    "name": "Retro Family Board Game",
    "description": "Premium toys & games item. Retro Family Board Game — quality you can trust, backed by a friendly return policy.",
    "price": 129.28,
    "category": "Toys & Games",
    "stock": 177,
    "imageUrl": "/images/logo-68.svg"
  },
  {
    "name": "Notebook Fountain-Pen Pencil Case",
    "description": "Premium books & stationery item. Notebook Fountain-Pen Pencil Case — quality you can trust, backed by a friendly return policy.",
    "price": 28.28,
    "category": "Books & Stationery",
    "stock": 248,
    "imageUrl": "/images/logo-69.svg"
  },
  {
    "name": "Machine-Washable Reflective Pet Toy",
    "description": "Premium pet supplies item. Machine-Washable Reflective Pet Toy — quality you can trust, backed by a friendly return policy.",
    "price": 74.06,
    "category": "Pet Supplies",
    "stock": 22,
    "imageUrl": "/images/logo-70.svg"
  },
  {
    "name": "Professional Bluetooth Car Vacuum",
    "description": "Premium automotive item. Professional Bluetooth Car Vacuum — quality you can trust, backed by a friendly return policy.",
    "price": 272.39,
    "category": "Automotive",
    "stock": 122,
    "imageUrl": "/images/logo-71.svg"
  },
  {
    "name": "4K Ultra Rebuilt Monitor",
    "description": "Premium electronics item. 4K Ultra Rebuilt Monitor — quality you can trust, backed by a friendly return policy.",
    "price": 110.89,
    "category": "Electronics",
    "stock": 52,
    "imageUrl": "/images/logo-72.svg"
  },
  {
    "name": "Velvet Walnut Table",
    "description": "Premium furniture item. Velvet Walnut Table — quality you can trust, backed by a friendly return policy.",
    "price": 132.06,
    "category": "Furniture",
    "stock": 49,
    "imageUrl": "/images/logo-73.svg"
  },
  {
    "name": "Waterproof Travel Necklace",
    "description": "Premium wearables item. Waterproof Travel Necklace — quality you can trust, backed by a friendly return policy.",
    "price": 265.41,
    "category": "Wearables",
    "stock": 60,
    "imageUrl": "/images/logo-74.svg"
  },
  {
    "name": "Organic Small-Batch Almond Butter",
    "description": "Premium groceries item. Organic Small-Batch Almond Butter — quality you can trust, backed by a friendly return policy.",
    "price": 41.16,
    "category": "Groceries",
    "stock": 58,
    "imageUrl": "/images/logo-75.svg"
  },
  {
    "name": "Handmade Reinforced Belt",
    "description": "Premium accessories item. Handmade Reinforced Belt — quality you can trust, backed by a friendly return policy.",
    "price": 20.86,
    "category": "Accessories",
    "stock": 35,
    "imageUrl": "/images/logo-76.svg"
  },
  {
    "name": "Insulated Brushed Chopping Board",
    "description": "Premium home & kitchen item. Insulated Brushed Chopping Board — quality you can trust, backed by a friendly return policy.",
    "price": 196.25,
    "category": "Home & Kitchen",
    "stock": 75,
    "imageUrl": "/images/logo-77.svg"
  },
  {
    "name": "Hydrating Lavender Face Mask",
    "description": "Premium beauty & personal care item. Hydrating Lavender Face Mask — quality you can trust, backed by a friendly return policy.",
    "price": 91.45,
    "category": "Beauty & Personal Care",
    "stock": 74,
    "imageUrl": "/images/logo-78.svg"
  },
  {
    "name": "Portable Foldable Resistance Bands",
    "description": "Premium sports & outdoors item. Portable Foldable Resistance Bands — quality you can trust, backed by a friendly return policy.",
    "price": 368.31,
    "category": "Sports & Outdoors",
    "stock": 20,
    "imageUrl": "/images/logo-79.svg"
  },
  {
    "name": "Buildable Battery-Powered Card Game",
    "description": "Premium toys & games item. Buildable Battery-Powered Card Game — quality you can trust, backed by a friendly return policy.",
    "price": 83.59,
    "category": "Toys & Games",
    "stock": 84,
    "imageUrl": "/images/logo-80.svg"
  },
  {
    "name": "Refillable Eco-Friendly Cookbook",
    "description": "Premium books & stationery item. Refillable Eco-Friendly Cookbook — quality you can trust, backed by a friendly return policy.",
    "price": 61.34,
    "category": "Books & Stationery",
    "stock": 138,
    "imageUrl": "/images/logo-81.svg"
  },
  {
    "name": "Premium Quilted Cat Tree",
    "description": "Premium pet supplies item. Premium Quilted Cat Tree — quality you can trust, backed by a friendly return policy.",
    "price": 39.85,
    "category": "Pet Supplies",
    "stock": 97,
    "imageUrl": "/images/logo-82.svg"
  },
  {
    "name": "Compact Dash-Cam Tire Pump",
    "description": "Premium automotive item. Compact Dash-Cam Tire Pump — quality you can trust, backed by a friendly return policy.",
    "price": 170.96,
    "category": "Automotive",
    "stock": 57,
    "imageUrl": "/images/logo-83.svg"
  },
  {
    "name": "Noise-Cancelling USB-C Keyboard",
    "description": "Premium electronics item. Noise-Cancelling USB-C Keyboard — quality you can trust, backed by a friendly return policy.",
    "price": 208.5,
    "category": "Electronics",
    "stock": 30,
    "imageUrl": "/images/logo-84.svg"
  },
  {
    "name": "Rustic Leather Cabinet",
    "description": "Premium furniture item. Rustic Leather Cabinet — quality you can trust, backed by a friendly return policy.",
    "price": 186.68,
    "category": "Furniture",
    "stock": 54,
    "imageUrl": "/images/logo-85.svg"
  },
  {
    "name": "Slim Solar Earrings",
    "description": "Premium wearables item. Slim Solar Earrings — quality you can trust, backed by a friendly return policy.",
    "price": 172.75,
    "category": "Wearables",
    "stock": 115,
    "imageUrl": "/images/logo-86.svg"
  },
  {
    "name": "Artisan Roasted Spice Blend",
    "description": "Premium groceries item. Artisan Roasted Spice Blend — quality you can trust, backed by a friendly return policy.",
    "price": 4.64,
    "category": "Groceries",
    "stock": 69,
    "imageUrl": "/images/logo-87.svg"
  },
  {
    "name": "Premium Anti-Theft Watch Strap",
    "description": "Premium accessories item. Premium Anti-Theft Watch Strap — quality you can trust, backed by a friendly return policy.",
    "price": 185.24,
    "category": "Accessories",
    "stock": 215,
    "imageUrl": "/images/logo-88.svg"
  },
  {
    "name": "Vintage Tempered Coffee Maker",
    "description": "Premium home & kitchen item. Vintage Tempered Coffee Maker — quality you can trust, backed by a friendly return policy.",
    "price": 42.72,
    "category": "Home & Kitchen",
    "stock": 63,
    "imageUrl": "/images/logo-89.svg"
  },
  {
    "name": "Natural Rose Skincare Set",
    "description": "Premium beauty & personal care item. Natural Rose Skincare Set — quality you can trust, backed by a friendly return policy.",
    "price": 21.33,
    "category": "Beauty & Personal Care",
    "stock": 193,
    "imageUrl": "/images/logo-90.svg"
  },
  {
    "name": "Trail Non-Slip Dumbbell Set",
    "description": "Premium sports & outdoors item. Trail Non-Slip Dumbbell Set — quality you can trust, backed by a friendly return policy.",
    "price": 349.54,
    "category": "Sports & Outdoors",
    "stock": 95,
    "imageUrl": "/images/logo-91.svg"
  },
  {
    "name": "STEM Bluetooth Board Game",
    "description": "Premium toys & games item. STEM Bluetooth Board Game — quality you can trust, backed by a friendly return policy.",
    "price": 74.1,
    "category": "Toys & Games",
    "stock": 107,
    "imageUrl": "/images/logo-92.svg"
  },
  {
    "name": "Premium Eco-Friendly Notebook",
    "description": "Premium books & stationery item. Premium Eco-Friendly Notebook — quality you can trust, backed by a friendly return policy.",
    "price": 63.74,
    "category": "Books & Stationery",
    "stock": 44,
    "imageUrl": "/images/logo-93.svg"
  },
  {
    "name": "Premium Non-Slip Leash",
    "description": "Premium pet supplies item. Premium Non-Slip Leash — quality you can trust, backed by a friendly return policy.",
    "price": 155.45,
    "category": "Pet Supplies",
    "stock": 102,
    "imageUrl": "/images/logo-94.svg"
  },
  {
    "name": "High-Grip Inflatable Seat Cover",
    "description": "Premium automotive item. High-Grip Inflatable Seat Cover — quality you can trust, backed by a friendly return policy.",
    "price": 251.32,
    "category": "Automotive",
    "stock": 123,
    "imageUrl": "/images/logo-95.svg"
  },
  {
    "name": "Mini LED Monitor",
    "description": "Premium electronics item. Mini LED Monitor — quality you can trust, backed by a friendly return policy.",
    "price": 254.36,
    "category": "Electronics",
    "stock": 120,
    "imageUrl": "/images/logo-96.svg"
  },
  {
    "name": "Compact Oak Cabinet",
    "description": "Premium furniture item. Compact Oak Cabinet — quality you can trust, backed by a friendly return policy.",
    "price": 178.26,
    "category": "Furniture",
    "stock": 39,
    "imageUrl": "/images/logo-97.svg"
  },
  {
    "name": "Slim Anti-bacterial Bracelet",
    "description": "Premium wearables item. Slim Anti-bacterial Bracelet — quality you can trust, backed by a friendly return policy.",
    "price": 65.33,
    "category": "Wearables",
    "stock": 42,
    "imageUrl": "/images/logo-98.svg"
  },
  {
    "name": "Hand-Crafted Roasted Dark Chocolate",
    "description": "Premium groceries item. Hand-Crafted Roasted Dark Chocolate — quality you can trust, backed by a friendly return policy.",
    "price": 67.48,
    "category": "Groceries",
    "stock": 177,
    "imageUrl": "/images/logo-99.svg"
  }
];

export default products;
